spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: kmr
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false